# Generated by Django 2.0.7 on 2018-07-25 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0004_auto_20180725_0103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Earnings',
            new_name='Earning',
        ),
    ]
