# Generated by Django 2.0.7 on 2018-07-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0006_auto_20180725_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='week',
            field=models.DateField(blank=True, null=True),
        ),
    ]
