# Generated by Django 2.0.7 on 2018-07-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0007_auto_20180725_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='week',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
