# Generated by Django 2.0.7 on 2018-07-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0008_auto_20180725_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='week',
            field=models.CharField(max_length=50),
        ),
    ]
